documentation:
- changed-files:
  - any-glob-to-any-file:
    - 'docs/**'
    - README.md

area/install:
- changed-files:
  - any-glob-to-any-file:
      - 'lib/src/install.rs'
      - 'lib/src/install/**'

area/system-reinstall-bootc:
- changed-files:
  - any-glob-to-any-file:
      - 'system-reinstall-bootc/**'
