---
jobs:
  - job: tests
    trigger: pull_request
    targets:
      - fedora-40-x86_64
      - fedora-40-aarch64
    tmt_plan: /integration-build
    skip_build: true
    identifier: integration-test
