[package]
name = "bootc"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cgwalters/bootc"
readme = "README.md"
publish = false
rust-version = "1.63.0"

[dependencies]
anyhow = "1.0"
bootc-lib = { path = "../lib" }
clap = "3.2"
libc = "0.2.92"
tokio = { version = "1", features = ["macros"] }
log = "0.4.0"
tracing = "0.1"
tracing-subscriber = "0.2.17"
